### ISSUE TITLE
Add ability to change entry type in flow editor

### ISSUE THREAD

**Issue by paulrobertlloyd** [gerwitz/sitewriter#26]
I’m sure there’s a good reason why this isn’t possible, but given the different entry types available, it’d be helpful if you could change an entry type after you’ve created a flow.

**Comment by gerwitz** [comment]
I was actually planning to simplify the UI by taking "flows" out of the conceptual model, and orienting the site configuration around entry types. (#29)

This might be dangerous because it will require the tool to have a POV about entry types, but that's already true. (I don't want to pretend the "everything is just Microformats" abstraction of Micropub absolves us of understanding content.)

**Comment by paulrobertlloyd** [comment]
This makes sense. In fact, presented as “here are the types of things your micropub endpoint can receive, how do you want to respond to each post type“ may have meant me not running into the issues I did when I set up my first flow.
